import './globals.css'
import { Inter } from 'next/font/google'
import Provider from './context/AuthContext'
import Navbar from '@/components/ui/navbar'
import Footer from '@/components/ui/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'EAFC24',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        <Navbar/>
        {children}</Provider>
      </body>
    </html>
  )
}
